import { v4 as uuidv4 } from "uuid";
import BoxSet from "../models/BoxSet";

export const ReccomendedBoxSetsDataArr: BoxSet[] = [
  {
    uuid: uuidv4(),
    name: "Studio",
    maxSquareFeet: 700,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 10,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 9,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 5,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 2,
      },
    ],
  },
  {
    uuid: uuidv4(),
    name: "One Bedroom",
    maxSquareFeet: 900,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 15,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 13,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 7,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 3,
      },
    ],
  },
  {
    uuid: uuidv4(),
    name: "Two Bedroom",
    maxSquareFeet: 1200,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 22,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 20,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 10,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 6,
      },
    ],
  },
  {
    uuid: uuidv4(),
    name: "Three Bedroom",
    maxSquareFeet: 1600,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 32,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 30,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 15,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 10,
      },
    ],
  },
  {
    uuid: uuidv4(),
    name: "Four Bedroom",
    maxSquareFeet: 2000,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 40,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 35,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 20,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 13,
      },
    ],
  },
  {
    uuid: uuidv4(),
    name: "Five Bedroom",
    maxSquareFeet: 2500,
    boxes: [
      {
        uuid: uuidv4(),
        length: "16",
        width: "12",
        height: "12",
        distance_unit: "in",
        weight: "7",
        mass_unit: "lb",
        quantity: 45,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "16",
        height: "18",
        distance_unit: "in",
        weight: "15",
        mass_unit: "lb",
        quantity: 40,
      },
      {
        uuid: uuidv4(),
        length: "18",
        width: "18",
        height: "24",
        distance_unit: "in",
        weight: "20",
        mass_unit: "lb",
        quantity: 25,
      },
      {
        uuid: uuidv4(),
        length: "24",
        width: "20",
        height: "24",
        distance_unit: "in",
        weight: "25",
        mass_unit: "lb",
        quantity: 16,
      },
    ],
  },
];
